--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/eli/wallpaper/lion_galaxy_purple.jpg"

-- Special
background="#0B0A13"
foreground="#dfc7d9"
cursor="#dfc7d9"

-- Colors
color0="#0B0A13"
color1="#87607A"
color2="#60388A"
color3="#6D5292"
color4="#9E6297"
color5="#B459B3"
color6="#7C82BF"
color7="#dfc7d9"
color8="#9c8b97"
color9="#87607A"
color10="#60388A"
color11="#6D5292"
color12="#9E6297"
color13="#B459B3"
color14="#7C82BF"
color15="#dfc7d9"
