# Shell variables
# Generated by 'wal'
wallpaper='/home/eli/wallpaper/lion_galaxy_purple.jpg'

# Special
background='#0B0A13'
foreground='#dfc7d9'
cursor='#dfc7d9'

# Colors
color0='#0B0A13'
color1='#87607A'
color2='#60388A'
color3='#6D5292'
color4='#9E6297'
color5='#B459B3'
color6='#7C82BF'
color7='#dfc7d9'
color8='#9c8b97'
color9='#87607A'
color10='#60388A'
color11='#6D5292'
color12='#9E6297'
color13='#B459B3'
color14='#7C82BF'
color15='#dfc7d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
