--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/eli/currentPyWalTemplate.png"

-- Special
background="#111012"
foreground="#cbc2cb"
cursor="#cbc2cb"

-- Colors
color0="#111012"
color1="#80647F"
color2="#925390"
color3="#A95BA8"
color4="#AD67AC"
color5="#C171BF"
color6="#C372C1"
color7="#cbc2cb"
color8="#8e878e"
color9="#80647F"
color10="#925390"
color11="#A95BA8"
color12="#AD67AC"
color13="#C171BF"
color14="#C372C1"
color15="#cbc2cb"
