foreground   #cbc2cb
background   #111012
cursor       #cbc2cb

color0       #111012
color8       #8e878e
color1       #80647F
color9       #80647F
color2       #925390
color10      #925390
color3       #A95BA8
color11      #A95BA8
color4       #AD67AC
color12      #AD67AC
color5       #C171BF
color13      #C171BF
color6       #C372C1
color14      #C372C1
color7       #cbc2cb
color15      #cbc2cb
